site_name: Astrology Guide
theme:
  name: 'material'
  palette:
    scheme: 'slate'
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - search.highlight
    - search.suggest

extra_css:
  - css/custom.css

nav:
  - Home: index.md
  - Foundations: foundations.md
  - Zodiac Signs: zodiac-signs.md
  - Elements and Modalities: elements-modalities.md
  - Natal Charts: natal-charts.md
  - Planets: planets.md
  - Houses: houses.md
  - Transits: transits.md
  - Community: community.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.tasklist
  - toc:
      permalink: true

# Add this line to specify your repository name
repo_url: https://github.com/amacsmith/astrology-guide.git

# Add to configure the site to use GitHub Pages
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amacsmith/astrology-guide.git
